services:
  student-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/student_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8080"

  postgres:
    image: postgres:latest
    container_name: student-database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Strong(!)Password
      POSTGRES_DB: student_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@student.org.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: student-redis
    ports:
      - "6379:6379"
    volumes:
      - student_cache:/data
    restart: unless-stopped

volumes:
  postgres_data:
  student_cache:


