services:
  postgres:
    image: postgres:latest
    container_name: student-database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Strong(!)Password
      POSTGRES_DB: student_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@student.org.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: student-redis
    ports:
      - "6379:6379"
    volumes:
      - student_cache:/data
    restart: unless-stopped

volumes:
  postgres_data:
  student_cache: