
spring:
  application:
    name: Student
  datasource:
    url: jdbc:postgresql://database:5432/student_management
    username: admin
    password: Strong(!)Password
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  data:
    redis:
      host: cache
      port: 6379
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

jwt:
  secret: vNaxPh8J0ZOTnG9N2+QFZffQ0N7sz8A5VvsJp3dRnK0=
  expiration: 300000
session:
  expiration: 600000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true